# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb03db790795e54dd626636608171e8c"
name = "bs"
handle = "bs-45"
application_url = "https://iceland-saint-increasing-body.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c0eb237e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://iceland-saint-increasing-body.trycloudflare.com/auth/callback",
  "https://iceland-saint-increasing-body.trycloudflare.com/auth/shopify/callback",
  "https://iceland-saint-increasing-body.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
